# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirsttest():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.FIREFOX)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firsttest(self):
    self.driver.get("https://www.calculator.net/bmi-calculator.html")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(2) > .rbmark").click()
    self.driver.find_element(By.ID, "cage").click()
    self.driver.find_element(By.ID, "cage").send_keys("110")
    self.driver.find_element(By.NAME, "x").click()
    self.driver.find_element(By.ID, "ckg").click()
    self.driver.find_element(By.ID, "ckg").send_keys("90")
    self.driver.find_element(By.ID, "cheightmeter").click()
    self.driver.find_element(By.ID, "cheightmeter").send_keys("200")
    self.driver.find_element(By.NAME, "x").click()
  
